import Head from "next/head";
import Index from "@/components/templates/Index/Index";

export default function Home() {
  return (
    <>
      <Head>
        <title>Messenger</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Index />
      </div>
    </>
  );
}
