import Head from "next/head";
import IndexTemplate from "@/components/templates/Index/Index";
import React, { useEffect } from "react";
import { useUser } from "@/contexts/User/User";
import { useRouter } from "next/router";

const Index = () => {
  const { user } = useUser();
  const router = useRouter();

  useEffect(() => {
    if (!user) {
      router.push("/login");
    }
  }, [user]);

  return (
    <>
      <Head>
        <title>Messenger</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <IndexTemplate />
      </div>
    </>
  );
};
export default Index;
