import Head from "next/head";
import LoginTemplate from "@/components/templates/Login/Login";

export default function Login() {
  return (
    <>
      <Head>
        <title>Messenger</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <LoginTemplate />
      </div>
    </>
  );
}
